# Generated by Django 4.2.10 on 2026-02-21 06:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: +999999999",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "license_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "license_class",
                    models.CharField(
                        choices=[
                            ("a", "Class A"),
                            ("b", "Class B"),
                            ("c", "Class C"),
                            ("d", "Class D"),
                            ("e", "Class E"),
                        ],
                        default="b",
                        max_length=20,
                    ),
                ),
                ("license_issue_date", models.DateField()),
                ("license_expiry_date", models.DateField(db_index=True)),
                (
                    "license_status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                        ],
                        default="valid",
                        max_length=20,
                    ),
                ),
                ("employment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On Leave"),
                            ("terminated", "Terminated"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("medical_cert_expiry", models.DateField(blank=True, null=True)),
                ("training_cert_expiry", models.DateField(blank=True, null=True)),
                ("background_check_date", models.DateField(blank=True, null=True)),
                ("background_check_status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "drivers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriverViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("speeding", "Speeding"),
                            ("traffic_light", "Traffic Light Violation"),
                            ("unsafe_driving", "Unsafe Driving"),
                            ("parking", "Parking Violation"),
                            ("accident", "Accident"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("major", "Major"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("violation_date", models.DateField(db_index=True)),
                ("location", models.CharField(max_length=300)),
                (
                    "fine_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "db_table": "driver_violations",
                "ordering": ["-violation_date"],
            },
        ),
        migrations.CreateModel(
            name="DriverTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("safety", "Safety Training"),
                            ("defensive_driving", "Defensive Driving"),
                            ("hazmat", "Hazardous Materials"),
                            ("passenger", "Passenger Transport"),
                            ("cargo", "Cargo Handling"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("training_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("provider", models.CharField(max_length=200)),
                (
                    "certificate_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "db_table": "driver_trainings",
                "ordering": ["-training_date"],
            },
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["status", "created_at"], name="drivers_status_6a6825_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["license_number"], name="drivers_license_29348f_idx"
            ),
        ),
    ]
